language: python

cache:
  pip: true

matrix:
  include:
    - python: "2.7"
      env: TOX_ENV=py27

    - python: "3.5"
      env: TOX_ENV=py35

    - python: "3.6"
      env: TOX_ENV=py36

    - python: "3.7"
      dist: xenial
      env: TOX_ENV=py37

    - python: "3.8-dev"
      dist: xenial
      env: TOX_ENV=py38

    - python: "pypy"
      env: TOX_ENV=pypy

    - name: Linting
      python: "3.6"
      env: TOX_ENV=lint

install:
    - pip install tox

script: tox -e $TOX_ENV

after_success:
  # Submit data from .coverage to coveralls on success
  - pip install coveralls
  - coveralls
