sudo: required
dist: xenial
language: python
cache: pip

matrix:
  include:
    - python: "2.7"
      env: TOX_ENV=py27
    - python: "3.6"
      env: TOX_ENV=py36
    - python: "3.7"
      env: TOX_ENV=py37
    - python: "pypy"
      env: TOX_ENV=pypy
    - python: "3.7"
      env: TOX_ENV=lint

install:
    - pip install tox

script: tox -e $TOX_ENV

after_success:
  # Submit data from .coverage to coveralls on success
  - pip install coveralls
  - coveralls
