language: python

cache:
  pip: true

matrix:
  include:
    - python: "2.7"
      env: TOX_ENV=py27,py27-falcon-2.0

    - python: "3.5"
      env: TOX_ENV=py35,py35-falcon-2.0,py35-falcon-dev

    - python: "3.6"
      env: TOX_ENV=py36,py36-falcon-2.0,py36-falcon-dev

    - python: "3.7"
      dist: xenial
      env: TOX_ENV=py37,py37-falcon-2.0,py37-falcon-dev

    - python: "3.8-dev"
      dist: xenial
      env: TOX_ENV=py38,py38-falcon-2.0,py38-falcon-dev

    - python: "pypy"
      env: TOX_ENV=pypy,pypy-falcon-2.0

    - name: Linting
      python: "3.6"
      env: TOX_ENV=lint

install:
    - pip install tox

script: tox -e $TOX_ENV

after_success:
  # Submit data from .coverage to coveralls on success
  - pip install coveralls
  - coveralls
